### ISSUE TITLE
Error: Invalid Token

### ISSUE THREAD

**Issue by razordaze** [mecha-cms/mecha-cms#22]
- Unzipped the repo to a subdirectory on my dev server.
- Went to dev.server.com/subdirectory/install.php
- Entered:
 - Name **Dev Server**
 - Email **devserverversion@mailinator.com**
 - User **developer**
 - Pass **password**
- Submit 
...
- Response: **Invalid Token.**

This is not a terribly informative error, and I'm pretty sure this isn't what is supposed to happen while installing.

Screenshot:
![invalid-token-error](https://cloud.githubusercontent.com/assets/487308/8882119/899b1b12-31f9-11e5-8838-4c9ef27a103a.png)

**Comment by razordaze** [comment]
Okay, so this is ACTUALLY a file permissions error. Because PHP didn't install the repo, PHP didn't have permission to write / modify the directories / files, and specifically, the session file. 

Have you considered packaging the repo, so that it could be installed via Composer?

In any case, on to a *new* problem: (close this issue, open a new one?)

> # Not Found
>
> ###### The requested URL /subdirectory/manager/login was not found on this server. 
> ---------
> *Apache/2.4.7 Server at dev.server.com Port 80*

**Comment by tovic** [comment]
> Have you considered packaging the repo, so that it could be installed via Composer?

So, I just landed on the **Composer** documentation page and I thought I wouldn&rsquo;t packaging this repository for now. I&rsquo;m trying to make it as simple as possible, not relies on any external libraries, also, trying to not confuse the general users. This time, I use only two _external libraries_ (not created by me), **Font Awesome** and **Zepto**, and they are loaded into the web through a public CDN.

> close this issue, open a new one?

You don&rsquo;t have to. Have you tried accessing `/subdirectory/index.php` ?

Currently, I only tested **Mecha** on my local machine and my shared hosting where I run the **Mecha CMS** site. I never had problems with the installation until now. I need more users.

**Comment by razordaze** [comment]
Well, it's your repo, manage it as you see fit. This is simply feedback from a potential user who has tried, and failed, to install / use it. 

I was not suggesting you package the repo for so that *you* can use **Composer** to manage **Mecha CMS** dependencies. You should package it because it makes installing and keeping up to date with your repo *trivially simple & easy for users*. **I.e., add a functional composer.json to your repo = you get more users.**

Specifically, it would have made some of my permissions struggles vanish, as the PHP user on my dev droplet runs **Composer**, which creates the folders and files, and therefore has all the permissions it needed.


*Regarding the login issue:*
That is the URI that:
- the documentation told me to use
- the install script terminates at
- the login link on index.php points to

**Comment by tovic** [comment]
I&rsquo;ve set a default custom session save path to `false` in `SESSION` constant. Try to test the latest commit.
