### ISSUE TITLE
Dashboard and Custom Permalink Plugins

### ISSUE THREAD

**Issue by dahliadahlia** [mecha-cms/mecha-cms#47]
Hello! 

I installed the latest Mecha CMS today. I also installed the Custom Permalink and Dashboard plugin.

Issue One: 
Content (such as Articles) do not display on the front page. Front end pages are blank. Front end pages also use the Dashboard plugin theme, not the default theme. Here is a picture of the front end of the website after installing the Dashboard. No content, and tries to use the Dashboard theme.

![Mecha Issue #1](https://i.imgur.com/QG7b5mM.png)

Issue Two:
When I set the Custom Permalink to use "slug" only, urls still show the page base, such as /article/ Visiting a page without the Base results in 404.

**Comment by dahliadahlia** [comment]
On further inspection, removing the Dashboard plugin fixed the lack of content on the front end and fixed the custom permalink issues. 

Slug-only custom permalinks and content show up and work fine without the Dashboard plugin.

**Comment by tovic** [comment]
Sorry, I can not reproduce the same bug. Which **Mecha** version do you use? It should be in version `1.2.0-alpha.x` as I am still testing the CMS compatibility with the plugins.

Open `index.php` file and replace the `DEBUG` value to `true` then give me the error messages you see.

**Comment by dahliadahlia** [comment]
Hello!

Forgive me, it was my mistake. I pulled the latest (unstable) code. After pulling the latest alpha release, everything is in working order. 

Thank you for your troubles. :)
