### ISSUE TITLE
Rename Buttons

### ISSUE THREAD

**Issue by dahliadahlia** [mecha-cms/mecha-cms#48]
I have a suggestion. 

Perhaps rename the buttons "Uninstall" and "Remove" in the Plugins section. It's somewhat confusion and I've deleted plugins when I meant to deactivate them.

I suggest to rename "Uninstall" to "Deactivate". And "Remove" to "Delete", to avoid any more confusion.

**Comment by tovic** [comment]
I will change the text &ldquo;remove&rdquo; to &ldquo;delete&rdquo;, but still retain the text &ldquo;install/uninstall&rdquo; considering that the term &ldquo;install&rdquo; is closer to the meaning that I want. It also has an antonym &ldquo;remove&rdquo;, which can be confusing, as you have said.

![2016-01-29_094729](https://cloud.githubusercontent.com/assets/1669261/12666065/8db5174c-c66f-11e5-9b5c-e6416d69067a.png)

![2016-01-29_095014](https://cloud.githubusercontent.com/assets/1669261/12666068/91e8739a-c66f-11e5-9bd5-d1057b2538ba.png)

#### Synonym

 - instate: initiation
 - induct: take into an organization (take into the core)
 - plant: just like &ldquo;implant&rdquo; &rarr; to insert, to add a new organ to an organism (Mecha)

#### Antonym

 - stop &rarr; acceptable for me
 - displace &rarr; acceptable for me

We also have plugin hook(s) named as `on_plugin_mount` and `on_plugin_eject`, which would be closer to the term &ldquo;install&rdquo; and &ldquo;uninstall&rdquo;. If we use the term &ldquo;activate&rdquo; and &ldquo;deactivate&rdquo;, then it likely will force me to rename the plugin hook into `on_plugin_activate` and `on_plugin_deactivate` which is bad.

**Comment by dahliadahlia** [comment]
I understand your reasoning. Thank you for clarifying.

Delete is a better word for Remove, so I'm happy with that. :) It makes more sense when it sits next to Uninstall. Delete sounds like much more of a final removal from the system than Remove.
