### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by seeya** [mecha-cms/mecha-cms#57]
After entering the details in `knock.php` I get this error.
`The requested URL /manager/login was not found on this server.`
I tried deploying in sub directories, root directory but it all ends up the same.
`mod_rewrite` is also enabled.
Any idea?

**Comment by tovic** [comment]
Please give me the detail about your file location and the full URL format. Something ike this:

~~~ .no-highlight
www/
 └── mecha-1-2-6/
      └── index.php
~~~

~~~ .no-highlight
http://example.com/mecha-1-2-6/manager/login
~~~

Or go to the home page then click the login link at the bottom of your site to see whether the generated link from the installed CMS is different with the generated redirection link from the installer.

**Comment by seeya** [comment]
I manage to solve it, it was the mod_rewrite settings not being enabled under the apache2.conf file.
