### ISSUE TITLE
Update to Version 1.2.7 and Install the Category Plugin Makes the Blog Broken

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha-cms#61]
Hello developers,

I noticed the following today and although I have installed the new version. It was an update of the version 1.2.5 to version 1.2.7, and then I installed the categories plugin. Then the blog at http://wpzweinull.ch/cms/mecha was no longer accessible.

I now had to return the Version 1.2.5 and use without the plugin categories.

It was in a browser http error, but unfortunately I had no Error Logs and do not know what was the reason.

In your Developer Blog Mecha-cms.com I can already see the categories and the new version. For me it makes the blog broken, for whatever reason ;(

I do not know if you can help without more information to me. I'll leave it for the first time in the version 1.2.5.

I wanted to tell.

Thanks in advance.

**Comment by tovic** [comment]
What kind of error did you see? A blank white page or just a broken error page with _Times New Roman_ font as it usually caused by the `.htaccess` configuration?

Try installing a copy of the new **Mecha CMS** version in a separate folder first, don&rsquo;t just overwrite it, as explained in [this article](http://mecha-cms.com/article/migrating#reference:cms-update). Hope this help.

**Comment by AlexL777** [comment]
Very strange behavior of Mecha CMS. And I have now tried it with version 1.2.7 and even showed me Google Chrome in Frontend after a few minutes **http error 500**

The content of my .htaccess file looks like this:


```
# Set default charset utf-8
AddDefaultCharset UTF-8

# Block access to directories without a default document.
# You should leave the following uncommented, as you shouldn't allow anyone to
# surf through every directory on your server (which may includes rather private
# places such as the CMS's directories).
<IfModule mod_autoindex.c>
    Options -Indexes
</IfModule>

# PHP 5, Apache 1 and 2
<IfModule mod_php5.c>
    php_flag magic_quotes_gpc off
    php_flag magic_quotes_sybase off
    php_flag register_globals off
</IfModule>

# Force Internet Explorer to render pages in the highest available mode
# in the various cases when it may not.
# http://hsivonen.iki.fi/doctype/ie-mode.pdf
<IfModule mod_headers.c>
    Header set X-UA-Compatible "IE=edge"
    # `mod_headers` cannot match based on the content-type, however, this
    # header should be send only for HTML pages and not for the other resources
    <FilesMatch "\.(appcache|atom|crx|css|cur|eot|f4[abpv]|flv|gif|htc|ico|jpe?g|js|json(ld)?|m4[av]|manifest|map|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|tt[cf]|vcf|vtt|webapp|web[mp]|woff|xml|xpi)$">
        Header unset X-UA-Compatible
    </FilesMatch>
</IfModule>

# Prevent viewing of .htaccess file
<Files ~ "^\.ht">
    Order allow,deny
    Deny from all
    Satisfy all
</Files>

# gzip
<ifModule mod_gzip.c>
    mod_gzip_on Yes
    mod_gzip_dechunk Yes
    mod_gzip_item_include file \.(archive|cache|css|eot|hold|html?|js|jsonp?|md|php|pl|ttf|txt|xml)$
    mod_gzip_item_include handler ^cgi-script$
    mod_gzip_item_include mime ^text/.*
    mod_gzip_item_include mime ^application/.*
    mod_gzip_item_exclude mime ^image/.*
    mod_gzip_item_exclude file \.woff2?$
    mod_gzip_item_exclude rspheader ^Content-Encoding:.*gzip.*
</ifModule>

# The following expires headers are set pretty far in the future. If you
# don't control versioning with filename-based cache busting, consider
# lowering the cache time for resources such as style sheets and JavaScript
# files to something like one week.
<IfModule mod_expires.c>

    ExpiresActive on
    ExpiresDefault "access plus 1 month"

  # CSS
    ExpiresByType text/css "access plus 1 year"

  # Data interchange
    ExpiresByType application/json "access plus 0 seconds"
    ExpiresByType application/ld+json "access plus 0 seconds"
    ExpiresByType application/xml "access plus 0 seconds"
    ExpiresByType text/xml "access plus 0 seconds"

  # Favicon (cannot be renamed!) and cursor images
    ExpiresByType image/x-icon "access plus 1 week"

  # HTML components (HTCs)
    ExpiresByType text/x-component "access plus 1 month"

  # HTML
    ExpiresByType text/html "access plus 0 seconds"

  # JavaScript
    ExpiresByType application/javascript "access plus 1 year"

  # Manifest files
    ExpiresByType application/x-web-app-manifest+json "access plus 0 seconds"
    ExpiresByType text/cache-manifest "access plus 0 seconds"

  # Media
    ExpiresByType audio/ogg "access plus 1 month"
    ExpiresByType image/gif "access plus 1 month"
    ExpiresByType image/jpeg "access plus 1 month"
    ExpiresByType image/png "access plus 1 month"
    ExpiresByType video/mp4 "access plus 1 month"
    ExpiresByType video/ogg "access plus 1 month"
    ExpiresByType video/webm "access plus 1 month"

  # Web feeds
    ExpiresByType application/atom+xml "access plus 1 hour"
    ExpiresByType application/rss+xml "access plus 1 hour"

  # Web fonts
    ExpiresByType application/font-woff "access plus 10 year"
    ExpiresByType application/vnd.ms-fontobject "access plus 10 year"
    ExpiresByType application/x-font-woff "access plus 10 year"
    ExpiresByType application/x-font-ttf "access plus 10 year"
    ExpiresByType font/opentype "access plus 10 year"
    ExpiresByType image/svg+xml "access plus 10 year"

</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /cms/mecha/
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php?$1 [L,QSA]
</IfModule>

```

I only "RewriteBase /cms/mecha/" added.

Today I installed a few plugins and cleared the cache in the Blog.

From then the Mecha Blog was no longer accessible under **/cms/mecha**.

I used to not have these problems.

What else can I do? You see it now in the browser, which is displayed there.

**Comment by tovic** [comment]
> Today I installed a few plugins and cleared the cache in the Blog.

> **From then** the Mecha Blog was no longer accessible under /cms/mecha.

So, your site broken after you install some plugins but just fine on first installation? (because to install a plugin you must be able to access the plugin manager page, right?)

What plugins did you re-install? Are they came from the latest version or did you just copy the plugins folder from the old site?

**Comment by AlexL777** [comment]
Yes, on the Plugin Manager in the backend, I was able to access normal. I then the whole installation Mecha with a FTP backup restored.

I have the Category plugin reinstalled and had to again install the TOC plugin because it did not work.

It often happens that when I newly installed in the Plugin Manager plugin that my Mecha Blog on the home page has not been reached then.

But the Mecha backend I could do something.

Now I have only the Mecha CMS version 1.2.5. and there seems to work at first glance everything. I'll leave it that way.

**Comment by tovic** [comment]
Did you also re-upload the manager plugin? If so then maybe that was caused the problem.

My concern now is to keep in mind with the _everything is a plugin_ principle. So in the future, you may will see **Mecha** as a PHP framework with a blog plugin in it.

Please do not overwrite the [default plugins].

**Comment by AlexL777** [comment]
Yes, I suppose I've re-uploaded and the Manager Plugin.

Today I just wanted to install the Category Plugin from the backend out again. Although this worked, but immediately after my Mecha Blog was no longer accessible in the browser.

I do not know which comes like this.

The Mecha Version 1.2.7 I can not use and shame with the Category plugin then. Apparently harmonizes something in the system not to each other.

But nice to know that you want to develop the CMS as a PHP Framework and very good that it will be doing a blog. I am as a user here!

**Comment by tovic** [comment]
> **Although this worked**, but immediately after, my Mecha Blog was no longer accessible in the browser.

When did it worked? In the backend side? Do you have the right to access the Apache log files? There maybe some log data about the HTTP error 500.

I recommend you to try to contact your web hosting provider.

**Comment by tovic** [comment]
Really, I think this is just because of some obsolete plugins that you re-upload. My friend just successfully installed the CMS here &rarr; hxxp://bayuhandono[dot]com

Try to check the download page again of the old plugins. Maybe there are some new release versions.

**Comment by AlexL777** [comment]
Thanks for your advice. Something it was with me and I leave my Mecha installation in version 1.2.5.

That's fine so and I'm waiting then on your next version of this CMS. Maybe it works for me then.

Thank you for your time.
