### ISSUE TITLE
REQ: otomatis publish

### ISSUE THREAD

**Issue by kudataz** [mecha-cms/mecha-cms#62]
halo min, request donk? klo boleh sih hhee..
jadi gini, di blogger kan ad publish berdasarkan tanggal, maksute otomatis publish
nah saya harap mecha bisa gitu juga min..

**contoh:** saya punya 10 post ato lebih..
lalu saya post semuanya dlm 1hari,
lalu perharinya otomatis publish gitu 1/1 sampai ke 10 post tadi selama 10 hari.
jadi kita gk musti update setiap hari dalam bloging, tapi blog update setiap hari..

bagaimana mnurut mimin?
sy harap si di rilis hhee.. #ngarep 

Salam,
**keep fight mecha! go indonesia!**

**Comment by tovic** [comment]
Kalau _update_ otomatis biasanya pakai _cron job_ mas, tapi bisa juga pakai PHP mentah, cuma syaratnya blog harus sudah jelas dikunjungi oleh pengunjung secara berkala supaya fungsi PHP tersebut tereksekusi sehingga program _timer_ di dalamnya akan melakukan cek waktu kadaluarsa setiap kali blog dikunjungi. Jika waktu sudah memenuhi syarat, posting akan dipublikasikan, begitu.

Ide bagus mas, cuma Saya masih ubek-ubek ke plugin yang sederhana dulu seperti _sticky post_ misalnya, yang sudah biasa ada pada CMS blog standar.

**Comment by tovic** [comment]
https://cron-job.org
