### ISSUE TITLE
What About the Development of Mecha CMS

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha-cms#66]
Hello dear developers of Mecha CMS. It is my understanding that the Mecha CMS is about to stop and it would be a pity if you no longer could it evolve.

Your website under http://mecha-cms.com is already off, probably because the web hosting could no longer be paid ?!

This is a sad development and I personally think the Mecha CMS very good. Therefore, I would support you this time. I make you a transfer in the next few days 15 Euro by bank transfer. This will be a bank transfer or perhaps you own a Paypal account ?! Then I call a PayPal address, so that I can transfer. There I can make it.

I hope that you can attract something this small donation.

I like Mecha CMS and have it installed today again in the new version.

So chin up and we make the CMS together known :)

Yours sincerely, Alexander

**Comment by tovic** [comment]
Hi, yes. Thanks a lot for your concern about this CMS development _sir_. It is still being developed silently. Even, I have rewrite the [text editor API](https://github.com/tovic/text-editor#plugins) for the [future version](https://github.com/mecha-cms/mecha-cms-v2) of **Mecha CMS** (this version will be focused to be developed for PHP7). But this year I really be in focus on the study I was in the **nursing** field. I decided to be a nurse in the real world, and a web developer in the virtual world. Sorry if this sounds very personal. Don&rsquo;t worry, the CMS is still growing, just slightly slowed.

Yes, donations may be very necessary for this. I just was not in the same mood for now. I have patients.

About my **PayPal** account, you could certainly see a _donate_ button at the bottom of the plugin or shield you use, in the manager page. It should able to lead you to the donation page for this CMS.

Sorry if you expectation is about when the new blog posts will be published again. Perhaps, even if the site is back on, the blog posts I can write will not going to be as often as before. but I will answer any questions from my users, about this CMS, about bugs, about tips and hacks, future plans, etc.

Thanks for using the results of my work. It means a lot.

**Comment by AlexL777** [comment]
Hi,

I am pleased to hear that you still aspire to develop and I will work with the CMS Mecha continue. In addition, I report about it in German, so that German CMS user can get to know it.

On your official website I saw the Donate button and when Mecha-cms.com is back online, I'll make a small donation.

I can me already think that it is hard, real to have another job and make virtually completely something else. But that does not bother me if it is so. I'll piecemeal promotion of this flat file CMS in its own portfolio so that more web users know about it. Maybe it already use another German users. So exactly I can not know it.

Then I'm looking forward to Mecha CMS 2.0.x and I will certainly follow :smile:
